### ISSUE TITLE
`.filter()` can't handle union of arrays

### ISSUE THREAD

**Issue by mattiaz9** [total-typescript/ts-reset#168]
Example:
```ts
type ClientA = { firstName: string; lastName: string; isAdmin: boolean }
type ClientB = { fullName: string; isAdmin: boolean }
type ClientList = ClientA[] | ClientB[]

const list: ClientList = []
const admins = list.filter(c => c.isAdmin)
//                         ^^^^^^^^^^^^^^
// Error: Argument of type '<T>(c: T | undefined) => any' is not assignable to parameter of type 'BooleanConstructor'. 
// Type '<T>(c: T | undefined) => any' provides no match for the signature 'new (value?: any): Boolean'
```

In this example both `ClientA` and `ClientB` has a common field `isAdmin` but `.filter()` can't handle this union.

Removing `ts-reset` fixed the error.
Also changing the type to `(ClientA | ClientB)[]` fixed the error, but it can be inconvenient in some cases because of a forced type cast.

**Comment by RedGuy12** [comment]
Looks like using a generic fixes this error:
```ts
filter<P extends (value: T, index: number, array: T[]) => unknown>(
	predicate: P,
	thisArg?: unknown,
): P extends BooleanConstructor ? NonFalsy<T>[] : T[];
```
![image](https://github.com/total-typescript/ts-reset/assets/61329810/8b6c82f4-4ab9-48d7-b064-0151892101c1)
![image](https://github.com/total-typescript/ts-reset/assets/61329810/e7209300-7d61-404b-8e5a-7951636c7bc4)

**Comment by mattpocock** [comment]
This was fixed upstream in TS I think!

**Comment by m-radzikowski** [comment]
Unfortunately, this still occurs with the latest TypeScript 5.3.3.

**Comment by sillvva** [comment]
Yeah, this is weird.

![CleanShot 2024-03-17 at 09 54 10@2x](https://github.com/total-typescript/ts-reset/assets/5138384/e1ae5005-e840-4ceb-a6d9-b655f5c30a59)
![CleanShot 2024-03-17 at 09 53 18@2x](https://github.com/total-typescript/ts-reset/assets/5138384/df235f83-23db-41db-b42f-40ecaa160661)

**Comment by mattpocock** [comment]
Looks fixed in this playground:

https://www.typescriptlang.org/play?#code/C4TwDgpgBAwgNgSwgO2AQSgXigbygMwQCcBnYAOQEMBbCALijKIWQHMBuKOSsq2hpiw5QEJNABNqLBgCMA9nLgRKyKAF8AUKEixEKYACEsuAgFc4cPvUbBmbTqIlTkshUpXqt4aPCSoAMqLAxr76aADaALpQAD66foZRGhoAxnLIZFxBDKEBQcZJaRnBlJIsJMaIZAB0hHDAEEQAFClYAHxQKdWOZcgAlEA

**Comment by sillvva** [comment]
@mattpocock you forgot to add `import "@total-typescript/ts-reset";`. Doing so breaks that code.

https://www.typescriptlang.org/play?ssl=1&ssc=9&pln=1&pc=35#code/JYWwDg9gTgLgBAIgAIwjAhgGwLQwJ5gCmAzgMZTBgwD0Mx2UJhMCA3AFDv5FwDCmwQgDsYAQTgBeOAG84AM2BRiMAHLoQhAFxxlFIQHNWcTOmVqN23cANHgxUQBMQ17QCMIETIXRC4AXy4CQj4BYRgAIUkZeQBXTExzLR0YPUM4O0dnITcPLx9-QJ5+QREAGTt4KWKw0QBtAF04AB8QkoiGzlIIIWVjCu1qsoqojq6e+HQna2IogWUAOgVMGEIoAApSSQA+OFJ5jKmhAEogA

**Comment by sillvva** [comment]
Hmm. Looks like the above solution breaks type predicate filters.

```ts
// With the interface
const list1 = ["0", 0, false];
const list2 = list1.filter((v): v is number => typeof v === "number");
//    ^? (string | number | true)[]
console.log(list2); // 0

// Without the interface
const list1 = ["0", 0, false];
const list2 = list1.filter((v): v is number => typeof v === "number");
//    ^? number[]
console.log(list2); // 0
```

**Comment by danvk** [comment]
This is actually a pretty fundamental problem with the ts-reset approach that I think will be hard to fix. https://github.com/microsoft/TypeScript/pull/53489 added special logic for calling methods on `A[] | B[]`. If there are no overloads that work on `A[] | B[]` then it tries `(A | B)[]` instead. When you add a `.filter(Boolean)` overload, there's always one valid overload and the fallback never triggers.

I think adding an overload to `BooleanConstructor` itself might be a more promising approach (https://github.com/microsoft/TypeScript/issues/16655) but it also has some issues, see [this thread](https://twitter.com/danvdk/status/1773856977174859922).

**Comment by RedGuy12** [comment]
```ts
declare global {
	interface Array<T> {
		filter<S extends T>(
			predicate: (value: T, index: number, array: readonly T[]) => value is S,
			thisArg?: undefined,
		): S[]; // duplicated from DOM types
		filter<P extends (value: T, index: number, array: T[]) => unknown>(
			predicate: P,
			thisArg?: unknown,
		): (P extends BooleanConstructor ? NonFalsy<T> : T)[];
	}
}
```
I've been using this solution without problems for a while, although I haven't looked much into why it works. Interstingly, the overloads have to be in this order for it to work. The `BooleanConstructor` overload must override the predefined DOM overload and duplicating the DOM overload somehow prevents that.
[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYghgGwM4igXigM0U6AfKABigICJSSoA7AVwQUpqoBMJMBLKiZgKFEigA5APZV4yEAB4AKgD50UAKIAPAMYIarGQBpYOELIDcPTsAgAnbKugBBc+bhS5UAN48AkBwRnzkgMpQEMpmLEhQcgAUHu5g5tzsqnBmAFxQEQBuiDQQqdK6nKzKqbQAtgBGFrpw9o6pcXDMogio0gDaALoAlOjymRrQ7GF+2tHAABaDdgDmAPypTKwcXMwj7p2pfh2GUAD0O1DMNGAICUncWObCJVAAIgDyALJQ-BBIHl4+kgAKgcEQoWk+tlcvkWEFijRypUoNUHCBch1umh5EwANZUYQAdyosii7hicWYpxSUAAQsJhAgIHAqABhURIYDmGiqYDCcyrdzjSbmWbzKjorFUVbrNI-IIhZhhcmU6l0hlMlls8xQGZCUTiFAyeS5TpbHgAXx4PFUCqgJ0ZAEYFK1SIRSLpCLpsMgIO1jKaqIzzYNgAAmBQW4CWgB0HwsEQyovSUEG1EhFRVyOe4AgwkwUBjaGzUFIpUTpE6xj2UFLUAAemr8xYOsaXlBaSd-sAbAoXFh2OZGYI4CUclBGeZOFNtgg4N3e-3B8PtpNmCVOKkyhSqTSoEb6432M3SW2sHQED2+6lp1QR7GkDZ54uoMvZWuN6mG02qMAADK+hRb5s2DqUb+vqStaet6QapAB76fhgwFmg0C5eoGvphuw3gRqoPRQKoIZzvBnQ8CWZaVmkEGtgQEGknq7RAA)

**Comment by Eld0ud** [comment]
I have another similar issue :
```
type TestUnion = (string | null)[] | string[]
const list: TestUnion = []
const testResult = list.filter(Boolean)
//    ^? (string | null)[]
```
